import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Badge } from '@/components/Badge'
import { Trust } from '@/types'
import { Button } from '@/components/Button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Badge 
        trust={Trust.VERIFY}
      />
      <Button 
      icon={<img src="/icons/qr.svg" />}
      >
        Hello world
      </Button>
    </>
  )
}
