import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from './Home.module.scss'
import { Badge } from '@/components/Badge'
import { Trust } from '@/types'
import { Button } from '@/components/Button'
import { ConnectKitButton } from 'connectkit'
import { useAccount } from 'wagmi'
import { Logo } from '@/components/Logo'


const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  const { address, isConnecting, isDisconnected } = useAccount();
  return (
    <div className={styles.Home}>
      <Head>
        <title>Confide ID</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        !address && <Onboarding />
      }
      {
        address && <Home />
      }


    </div>
  )
}

const Onboarding = () => {
  return <>
    <Logo />
    <ConnectKitButton />
  </>
}

const Home = () => {
  const { address, isConnecting, isDisconnected } = useAccount();

return (
  <>
      <Badge 
        trust={Trust.VERIFY}
      />
      <Button 
      icon={<img src="/icons/qr.svg" />}
      >
        Hello world
      </Button>
      <ConnectKitButton />
      <Logo />
    </>
)

}